#!/bin/bash

set -eu
source hooks/config


_section "1. Push all images"

DOCKER_REPO="${DOCKER_REPO//index.docker.io\/}"
for arch in ${build_architectures[@]}; do
    _header "Pushing ${DOCKER_REPO}:${CACHE_TAG}-${arch}"
    docker push ${DOCKER_REPO}:${CACHE_TAG}-${arch}
done


_section "2. Build and push manifest"
DOCKER_REPO="index.docker.io/${DOCKER_REPO}"
manifests=""

for arch in ${build_architectures[@]}; do
    manifests="${manifests} ${DOCKER_REPO}:${CACHE_TAG}-${arch}"
done

_header "Creating manifest ${DOCKER_REPO}:${CACHE_TAG}"
docker manifest create ${DOCKER_REPO}:${CACHE_TAG} $manifests

_header "Annotating manifest"
for arch in ${build_architectures[@]}; do
    docker manifest annotate ${DOCKER_REPO}:${CACHE_TAG} \
           ${DOCKER_REPO}:${CACHE_TAG}-${arch} \
           --os linux \
           --arch ${docker_to_manifest_map[${arch}]}
done

header "Inspecting manifest ${DOCKER_REPO}:${CACHE_TAG}"
docker manifest inspect ${DOCKER_REPO}:${CACHE_TAG}

_header "Pushing manifest ${DOCKER_REPO}:${CACHE_TAG}"
docker manifest push --purge ${DOCKER_REPO}:${CACHE_TAG}
